### ISSUE TITLE
Import list for .par file does not match Bazel stub script

### ISSUE THREAD

**Issue by duggelz** [google/subpar#12]
See [issue 10](https://github.com/google/subpar/issues/10) for larger context.

When a workspace has no name, its files get added to the runfiles tree and .par file under the directory '**main**'.  The Bazel produced stub script adds this directory to sys.path automatically.  The .par file code in subpar/runtime/support.py should as well.

**Comment by gnufreak** [comment]
I've created a pull request at https://github.com/google/subpar/pull/13 that includes workspace names in the import_roots, regardless if the bazel workspace name is explicitly set by the user.

Thanks,
Marcin

**Comment by duggelz** [comment]
Should be fixed now.
