### ISSUE TITLE
Why is the generated dpkg_parser having a #!/usr/bin/python3 shebang?

### ISSUE THREAD

**Issue by kovkev** [google/subpar#120]
Hi subpar contributors! I posted in `distroless` that I saw the generated file contains a shebang that doesn't point anywhere. I run the new MacOS so there can't be a /usr/bin/python3 file there.

I was wondering how can I see where is subpar reading the python3 path from?

https://github.com/GoogleContainerTools/distroless/issues/434

**Comment by chanseokoh** [comment]
Please close this. It is an issue in distroless. subpar isn't related.
