### ISSUE TITLE
par files are already perl archives

### ISSUE THREAD

**Issue by tehmoth** [google/subpar#18]
[Perl Archive Toolkit](https://metacpan.org/pod/PAR) already creates .par files since 2002 at least.  Perhaps go with PYAR/.pyar?

**Comment by duggelz** [comment]
Naming things is hard.  I started using the .par extension inside Google around 2002 as well, based on the analogy with .jar files.

The file extension is not hardcoded into anything but the par_binary() macro in subpar.bzl.  It's a 5 line function, it would be pretty easy for you to make your own.

PEP 441 suggests .pyz and .pyzw, although .par files don't completely fit that scheme.  Bazel has some preliminary support to create Python .zip files, but I would argue that's way too generic an extension.

**Comment by duggelz** [comment]
I'm going to close this issue.  I hear what you're saying, but I'm going to keep things as is for now.  You might raise this with the Bazel project, since I would probably follow them if they came up with something reasonable.
