### ISSUE TITLE
External Repositories

### ISSUE THREAD

**Issue by mirzazadeh** [google/subpar#19]
Looks it does not work when we have external repositories. I am using it woth protobuf repository, and when I run .par file it says it can not import files from external repository. 
Here is .par file contents: As can be seen files from python/google/protobuf are in one place, their `__init__.py` files are in different places.

`
./protobuf
./protobuf/python
./protobuf/python/google
./protobuf/python/google/protobuf
./protobuf/python/google/protobuf/descriptor_database.py
./protobuf/python/google/protobuf/pyext
./protobuf/python/google/protobuf/pyext/cpp_message.py
./protobuf/python/google/protobuf/text_encoding.py
./protobuf/python/google/protobuf/message.py
./protobuf/python/google/protobuf/service_reflection.py
./protobuf/python/google/protobuf/field_mask_pb2.py
./protobuf/python/google/protobuf/proto_builder.py
./protobuf/python/google/protobuf/type_pb2.py
./protobuf/python/google/protobuf/descriptor_pool.py
./protobuf/python/google/protobuf/api_pb2.py
./protobuf/python/google/protobuf/duration_pb2.py
./protobuf/python/google/protobuf/source_context_pb2.py
./protobuf/python/google/protobuf/text_format.py
./protobuf/python/google/protobuf/empty_pb2.py
./protobuf/python/google/protobuf/descriptor_pb2.py
./protobuf/python/google/protobuf/wrappers_pb2.py
./protobuf/python/google/protobuf/service.py
./protobuf/python/google/protobuf/reflection.py
./protobuf/python/google/protobuf/compiler
./protobuf/python/google/protobuf/compiler/plugin_pb2.py
./protobuf/python/google/protobuf/json_format.py
./protobuf/python/google/protobuf/internal
./protobuf/python/google/protobuf/internal/encoder.py
./protobuf/python/google/protobuf/internal/type_checkers.py
./protobuf/python/google/protobuf/internal/wire_format.py
./protobuf/python/google/protobuf/internal/_parameterized.py
./protobuf/python/google/protobuf/internal/containers.py
./protobuf/python/google/protobuf/internal/well_known_types.py
./protobuf/python/google/protobuf/internal/testing_refleaks.py
./protobuf/python/google/protobuf/internal/python_message.py
./protobuf/python/google/protobuf/internal/api_implementation.py
./protobuf/python/google/protobuf/internal/enum_type_wrapper.py
./protobuf/python/google/protobuf/internal/decoder.py
./protobuf/python/google/protobuf/internal/message_listener.py
./protobuf/python/google/protobuf/timestamp_pb2.py
./protobuf/python/google/protobuf/struct_pb2.py
./protobuf/python/google/protobuf/any_pb2.py
./protobuf/python/google/protobuf/descriptor.py
./protobuf/python/google/protobuf/message_factory.py
./protobuf/python/google/protobuf/symbol_database.py
./__main__.py
./__main__
./__main__/external
./__main__/external/protobuf
./__main__/external/protobuf/__init__.py
./__main__/external/protobuf/python
./__main__/external/protobuf/python/google
./__main__/external/protobuf/python/google/protobuf
./__main__/external/protobuf/python/google/protobuf/pyext
./__main__/external/protobuf/python/google/protobuf/pyext/__init__.py
./__main__/external/protobuf/python/google/protobuf/__init__.py
./__main__/external/protobuf/python/google/protobuf/__init__.pyc
./__main__/external/protobuf/python/google/protobuf/compiler
./__main__/external/protobuf/python/google/protobuf/compiler/__init__.py
./__main__/external/protobuf/python/google/protobuf/internal
./__main__/external/protobuf/python/google/protobuf/internal/__init__.py
./__main__/external/protobuf/python/google/__init__.py
./__main__/external/protobuf/python/google/__init__.pyc
./__main__/external/protobuf/python/__init__.py
./__main__/external/__init__.py
./__main__/external/six_archive
./__main__/external/six_archive/__init__.py
./__main__/base
./__main__/base/__init__.py
./__main__/base/my_program.py
./subpar
./subpar/runtime
./subpar/runtime/__init__.py
./subpar/runtime/support.py
./subpar/__init__.py
./six_archive
./six_archive/six.py
`

**Comment by duggelz** [comment]
Can you point me to your code and BUILD file?

**Comment by mirzazadeh** [comment]
[test.zip](https://github.com/google/subpar/files/560225/test.zip)

Please see the attached test workspace. Note the target main.par depends on @protobuf//:python_srcs indirectly (I could not declare dependency explicitly due to visibility rules), and @protobuf//:python_srcs  includes the module I have imported in main.py (namely json_format.py)
