### ISSUE TITLE
Readme needs to show the actual build command

### ISSUE THREAD

**Issue by dmitry-xnor** [google/subpar#30]
If I wasn't an ex-googler, I wouldn't know that in order to build a `*.par` you need to add `.par` to the name of the target. I.e. do
```
bazel build //bar/baz/quux.par
```
Even though the target is just `quux`.

**Comment by dmitry-xnor** [comment]
Thanks for putting this together, BTW. This is great!

**Comment by mattmoor** [comment]
Yeah, fwiw given that it is a separate rule I was a little surprised by this myself.

**Comment by duggelz** [comment]
I'll document this, and also fix the WORKSPACE sample code which no longer works in newer versions of Bazel.
