### ISSUE TITLE
Subpar ignores Bazel imports

### ISSUE THREAD

**Issue by calder** [google/subpar#47]
Subpar ignores Bazel py_library `imports` attributes. This is needed by any workspace with interdependent Python setuptools packages.

The TODO currently references a Buganizer issue: https://github.com/google/subpar/blob/master/subpar.bzl#L62

**Comment by calder** [comment]
Minimal example:

* `WORKSPACE`
* `foo/`
  * `BUILD`
  * `foo/`
    * `__init__.py`
    * `lib.py`
    * `main.py`

`WORKSPACE`:
```python
git_repository(
    name = "subpar",
    remote = "https://github.com/google/subpar",
    tag = "1.0.0",
)
```
`foo/BUILD`:
```python
load("@subpar//:subpar.bzl", "par_binary")

py_library(
    name = "foo",
    srcs = ["foo/lib.py"],
    imports = ["."],
)

par_binary(
    name = "foo_main",
    srcs = ["foo/main.py"],
    main = "foo/main.py",
    deps = [
        ":foo",
    ],
)
```
`foo/foo/__init__.py`: empty
`foo/foo/lib.py`:
```python
x = 123
```
* `foo/foo/main.py`:
```python
from foo.lib import x

print "x = %d" % x
```

**Comment by duggelz** [comment]
Currently blocked on bazel: https://github.com/bazelbuild/bazel/issues/2617

**Comment by duggelz** [comment]
Actually, in this case, it should work, but my brittle workaround is finding the wrong `foo` first.  I should be able to reorder the heuristic.
